CREATE DATABASE plc

USE plc

CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    date_created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_login TIMESTAMP NULL
);

CREATE TABLE data (
    id INT PRIMARY KEY AUTO_INCREMENT,
    temperature FLOAT DEFAULT 0.0,
    humidity FLOAT DEFAULT 0.0,
    tvoc FLOAT DEFAULT 0.0,
    co2 FLOAT DEFAULT 0.0,
    pm25 FLOAT DEFAULT 0.0,
    time TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
)