CREATE DATABASE plc

USE plc

CREATE TABLE data (
    id INT PRIMARY KEY AUTO_INCREMENT,
    temperature FLOAT DEFAULT 0.0,
    humidity FLOAT DEFAULT 0.0,
    tvoc FLOAT DEFAULT 0.0,
    co2 FLOAT DEFAULT 0.0,
    pm25 FLOAT DEFAULT 0.0,
    time TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
)